# Generated by Django 2.1 on 2018-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2044)),
                ('src_id', models.CharField(blank=True, max_length=24, null=True)),
                ('dataset', models.CharField(blank=True, max_length=2044, null=True)),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
    ]
